# Generated by Django 3.0 on 2020-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_t',
            fields=[
                ('usr_name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('usr_password', models.CharField(max_length=30)),
                ('power', models.IntegerField()),
                ('n_news', models.IntegerField()),
            ],
        ),
    ]
