# Generated by Django 3.0 on 2020-03-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_usr_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('device_name', models.CharField(max_length=30)),
                ('device_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='usr_t',
            old_name='n_news',
            new_name='laboratory',
        ),
    ]
