# Generated by Django 3.0 on 2020-03-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20200325_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='buy_name',
            field=models.CharField(default='赵世纪', max_length=30),
            preserve_default=False,
        ),
    ]
