# Generated by Django 3.0 on 2020-03-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_device_buy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='buy_name',
            field=models.CharField(max_length=100),
        ),
    ]
