# Generated by Django 3.0 on 2020-03-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20200325_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='buy_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_time',
            field=models.DateTimeField(),
        ),
    ]
