# Generated by Django 3.0 on 2020-03-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20200325_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='laboratory',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usr_t',
            name='laboratory',
            field=models.CharField(max_length=30),
        ),
    ]
